//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcomage.WebConsole.Arcomage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Arcomage.IArcoServer")]
    public interface IArcoServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArcoServer/GetRandomCard", ReplyAction="http://tempuri.org/IArcoServer/GetRandomCardResponse")]
        string GetRandomCard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArcoServer/GetRandomCard", ReplyAction="http://tempuri.org/IArcoServer/GetRandomCardResponse")]
        System.Threading.Tasks.Task<string> GetRandomCardAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArcoServerChannel : Arcomage.IArcoServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArcoServerClient : System.ServiceModel.ClientBase<Arcomage.IArcoServer>, Arcomage.IArcoServer {
        
        public ArcoServerClient() {
        }
        
        public ArcoServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArcoServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArcoServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArcoServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRandomCard() {
            return base.Channel.GetRandomCard();
        }
        
        public System.Threading.Tasks.Task<string> GetRandomCardAsync() {
            return base.Channel.GetRandomCardAsync();
        }
    }
}
